# Generated by Django 4.2.5 on 2023-09-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pizza", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="ingredients",
            field=models.ManyToManyField(related_name="pizzas", to="pizza.ingredient"),
        ),
        migrations.DeleteModel(
            name="PizzaIngredient",
        ),
    ]
