# Generated by Django 4.2.5 on 2023-09-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pizza", "0002_pizza_ingredients_delete_pizzaingredient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="pizzasize",
            name="weight",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="base_price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="pizzasize",
            name="multiplier",
            field=models.PositiveIntegerField(),
        ),
    ]
